ARG BASE_OS
FROM "$BASE_OS"

ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get update

# Build tools
RUN apt-get install -y cmake build-essential python3 python3-venv git ninja-build

WORKDIR /workdir
