ARG BASE_OS="fedora:44"
FROM ${BASE_OS}

# Build tools
RUN dnf install -y \
  @development-tools gcc-c++ cmake python3 python3-devel ninja-build \
  SDL2-devel \
  wayland-devel wayland-protocols-devel libxkbcommon-devel \
  libX11-devel \
  libdrm-devel \
  libevdev-devel \
  libwebp-devel \
  mesa-libEGL-devel mesa-libGLES-devel mesa-libGL-devel mesa-libgbm-devel \
  && dnf clean all

WORKDIR /workdir
